{
  if (error.get() == null) {
    error.set(cause);
  }
  ctx.close();
  super.exceptionCaught(ctx,cause);
}
