{
  try {
    Task task=createTask(InvokableWithExceptionOnTrigger.class);
    task.registerExecutionListener(listener);
    task.startTaskThread();
    awaitLatch.await();
    task.failExternally(new Exception("external"));
    assertEquals(ExecutionState.FAILED,task.getExecutionState());
    triggerLatch.trigger();
    task.getExecutingThread().join();
    assertEquals(ExecutionState.FAILED,task.getExecutionState());
    assertTrue(task.isCanceledOrFailed());
    assertTrue(task.getFailureCause().getMessage().contains("external"));
    validateTaskManagerStateChange(ExecutionState.RUNNING,task,false);
    validateUnregisterTask(task.getExecutionId());
    validateListenerMessage(ExecutionState.RUNNING,task,false);
    validateListenerMessage(ExecutionState.FAILED,task,true);
  }
 catch (  Exception e) {
    e.printStackTrace();
    fail(e.getMessage());
  }
}
