{
  count++;
  if (!hasFailed && count >= failurePos) {
    hasFailed=true;
    throw new Exception("Test Failure");
  }
  return value;
}
