{
  int keyCnt=100;
  int valCnt=5;
  setOutput(this.output);
  addInputComparator(this.comparator1);
  addInputComparator(this.comparator2);
  getTaskConfig().setDriverPairComparator(PactRecordPairComparatorFactory.get());
  getTaskConfig().setDriverStrategy(DriverStrategy.CO_GROUP);
  final CoGroupDriver<PactRecord,PactRecord,PactRecord> testTask=new CoGroupDriver<PactRecord,PactRecord,PactRecord>();
  try {
    addInput(new UniformPactRecordGenerator(keyCnt,valCnt,true));
    addInput(new UniformPactRecordGenerator(keyCnt,valCnt,true));
  }
 catch (  Exception e) {
    e.printStackTrace();
    Assert.fail("The test caused an exception.");
  }
  final AtomicBoolean success=new AtomicBoolean(false);
  Thread taskRunner=new Thread(){
    @Override public void run(){
      try {
        testDriver(testTask,MockDelayingCoGroupStub.class);
        success.set(true);
      }
 catch (      Exception ie) {
        ie.printStackTrace();
      }
    }
  }
;
  taskRunner.start();
  TaskCancelThread tct=new TaskCancelThread(1,taskRunner,this);
  tct.start();
  try {
    tct.join();
    taskRunner.join();
  }
 catch (  InterruptedException ie) {
    Assert.fail("Joining threads failed");
  }
  Assert.assertTrue("Test threw an exception even though it was properly canceled.",success.get());
}
