{
  try {
    initEnvironmentManagers();
    setOutputAccessors();
    prepareInternal();
    prepare();
    run();
  }
 catch (  Throwable ex) {
    LOG.error(ex,ex);
    throw new Exception("Error during execution of task ",ex);
  }
 finally {
    output.close();
  }
}
