{
  try {
    final int NUM_RECORDS=100000;
    final TestData.Generator generator=new TestData.Generator(SEED,KEY_MAX,VALUE_LENGTH,KeyMode.RANDOM,ValueMode.CONSTANT,VAL);
    final MutableObjectIterator<Record> source=new TestData.GeneratorIterator(generator,NUM_RECORDS);
    LOG.debug("Initializing sortmerger...");
    Sorter<Record> sorter=new AsynchronousPartialSorter<Record>(this.memoryManager,source,this.parentTask,this.serializer,this.comparator,1.0);
    runPartialSorter(sorter,NUM_RECORDS,2);
  }
 catch (  Exception t) {
    t.printStackTrace();
    Assert.fail("Test failed due to an uncaught exception: " + t.getMessage());
  }
}
