{
  try {
    callUserFunction();
  }
 catch (  Exception e) {
    if (LOG.isErrorEnabled()) {
      LOG.error("Calling user function failed due to: {}",StringUtils.stringifyException(e));
    }
    throw new RuntimeException(e);
  }
}
