{
  try {
    executeTask(new FailingTestMapper(),1);
  }
 catch (  RuntimeException e) {
    if (!isCollectionExecution()) {
      Assert.fail();
    }
    Assert.assertEquals(EXCEPTION_STRING + ":0",e.getMessage());
  }
catch (  JobExecutionException e) {
    if (isCollectionExecution()) {
      Assert.fail();
    }
    Assert.assertEquals(EXCEPTION_STRING + ":1",e.getCause().getMessage());
  }
  executeTask(new TestMapper(),0);
}
