{
  if (!future.isSuccess()) {
    exceptionOccurred(future.cause() == null ? new Exception("Close failed.") : future.cause());
  }
}
