{
  int buildSize=1000;
  int probeSize=1000;
  try {
    Generator bgen=new Generator(SEED1,0,1024,KeyMode.SORTED,ValueMode.FIX_LENGTH);
    Generator pgen=new Generator(SEED2,0,1024,KeyMode.SORTED,ValueMode.FIX_LENGTH);
    final TestData.GeneratorIterator buildInput=new TestData.GeneratorIterator(bgen,buildSize);
    final TestData.GeneratorIterator probeInput=new TestData.GeneratorIterator(pgen,probeSize);
    doTest(buildInput,probeInput,bgen,pgen);
  }
 catch (  Exception e) {
    e.printStackTrace();
    Assert.fail("An exception occurred during the test: " + e.getMessage());
  }
}
